config/routes.rb
OverweightModelsExample::Application.routes.draw do
  resource :sign_ups, only: [:new, :create]
  
  resources :confirmations, only: [:edit, :update]
  resources :users, only: [:show]
  resource :session, only: [:new, :create]
  
  root to: 'sessions#new'
  

end

app/models/confirmation.rb
class Confirmation
  include BackedModel::Base
  backing_model :user
  
  attr_accessor :password
  
  validates :password,
            confirmation: true,
            presence: true
            
  def self.find(id)
    Confirmation.new User.find(id)
  end
  
  def initialize(user)
    self.user = user
  end
  
  def complete
    user.update_attributes :password => self.password if valid?
  end
  
  #move this to a module
  def attributes=(attributes)
    attributes.each { |attr_name, value| send(:"#{attr_name}=", value) }
  end
end

app/models/sign_up.rb
class SignUp
  include BackedModel::Base
  backing_model :user
  uses_uniquness_validations_against :user
  attr_accessor :nickname, :email
            
  validates :nickname,
            uniqueness: {message:'is already taken'},
            presence: true,
            length: { minimum: 5, maximum: 8 }
  
  validates :email,
            presence: true
  
  
  def initialize(params = {})
    self.nickname = params.try(:[],:nickname)
    self.email = params.try(:[],:email)
  end
  
  def complete
    if valid?
      user.nickname = nickname
      user.email = email
      user.save
    end
  end
  
  def user
    @user ||= User.new
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  
  field :nickname, type: String
  field :email, type: String
  field :password, type: String
  field :sign_in_count, type: Integer, default: 0
  
  scope :sign_up, lambda {|nickname, email| where(:nickname => nickname, :email => email) }
            
  def increment_sign_in_count
    self.sign_in_count += 1
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'
  protect_from_forgery
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  respond_to :html
  expose(:confirmation)
  
  def update
    confirmation.complete
    respond_with confirmation, :location => root_path  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :html
  
  expose(:user) { User.where(nickname: params[:nickname], password: params[:password]).first }
  
  def create
    unless user.nil?
      user.increment_sign_in_count
    else
      flash[:error] = "could not authorize"
    end
    
    respond_with user
  end
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  respond_to :html
  
  expose(:sign_up)
  
  def create
    sign_up.complete
    respond_with sign_up, :location => edit_confirmation_url(sign_up.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  
  expose :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OverweightModelsExample</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sign_up/new.html.haml
= form_for user, :url => sign_up_path do |f|
  - if user.errors.any?
    %ul
    - user.errors.full_messages.each do |msg|
      %li #{msg}
  = f.text_field :nickname, placeholder: 'nickname'
  = f.email_field :email, placeholder: 'email@example.com'
  = f.submit

app/views/sign_ups/new.html.haml
= form_for sign_up do |f|
  - if sign_up.errors.any?
    %ul
    - sign_up.errors.full_messages.each do |msg|
      %li #{msg}
  = f.text_field :nickname, placeholder: 'nickname'
  = f.email_field :email, placeholder: 'email@example.com'
  = f.submit

app/views/users/show.html.haml
.user
  %span #{user.nickname} has authorized #{user.sign_in_count} times
= link_to 'home', root_path